export const HARDDATA =  {
    "personal_info": {
        "image_path": "/assets/images/ebadi.JPG",
        "first_name": "Javad",
        "last_name": "Ebadi",
        "full_name": "Javad Ebadi",
        "job_subject": "FinTech",
        "job_title": "Physicist and Data Scientist at Middle East Bank",
        "facebook": "https://facebook.com/javad.ebadi.5",
        "instagram": "https://instagram.com/javad.ebadi.1990",
        "linkedin": "https://www.linkedin.com/in/javad-ebadi-3629a481",
        "github": "https://www.github.com/javadebadi",
        "youtube": "https://www.youtube.com/channel/UCu8q9SYoOYkuBdTmXBdAI4w",
        "twitter": "https://twitter.com/JavadEbadi9",
        "telegram": "https://t.me/javadebadi1990",
        "soundcloud": "https://soundcloud.com/user-226847302",
        "skype": "skype:javad.ebadi.abd?chat",
        "slideshare": "https://www.slideshare.net/JavadEbadi/",
        "inspire": "http://inspirehep.net/author/profile/J.Ebadi.1",
        "google_scholar": "https://scholar.google.com/citations?user=_Uz9iGAAAAAJ&hl=en",
        "researchgate": "https://www.researchgate.net/profile/Javad_Ebadi2",
        "goodreads": "https://www.goodreads.com/user/show/77636561-javad-ebadi",
        "anaconda": "https://anaconda.org/javadebadi",
        "stackoverflow": "https://stackoverflow.com/users/9600979/javad",
        "medium": "https://medium.com/@javad.ebadi.1990",
    },
    "navbar_items": [
        { "name": "Home", "route": "" },
        { "name": "Courses", "route": "/courses" },
        { "name": "CV", "route": "/cv" },
        { "name": "Blog", "route": "/blog" },
    ]
}