# Generated by Django 3.1.7 on 2021-03-31 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='degree',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
