# Generated by Django 3.1.7 on 2021-04-20 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20210331_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('code', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cv.country')),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='city_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cv.city'),
            preserve_default=False,
        ),
    ]
