# Generated by Django 3.1.7 on 2021-04-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20210420_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='study_field',
            field=models.CharField(blank=True, default='Science', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='thesis_title',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
