# Generated by Django 3.1.7 on 2021-05-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20210420_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='advisers',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
